version: "3"

services:
  database:
    image: "postgres" # use latest official postgres version
    restart: "no"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hzKD2b#KXk!hhseB=+U7P?A?
      POSTGRES_DB: VoteApp
    networks:
      - db_network
    volumes:
      - database-data:/var/lib/postgres/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"

networks:
  db_network:
    driver: bridge

volumes:
  database-data:
