version: "3.8"

services:
    database:
        image: mysql:8.0
        container_name: database
        ports:
            - "3307:3307"
        expose:
            - 3307
        environment:
            MYSQL_DATABASE: SurveyApp
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_USER: admin
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_HOST: '%'
            MYSQL_TCP_PORT: 3307
        volumes:
          - "./server/database/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql"

# networks:
#   db_network:
#     driver: bridge

# volumes:
#   database-data: